spring:
  application:
    name: dispatch-engine

  datasource:
    url: jdbc:postgresql://localhost:5433/vektor
    username: vektor
    password: vektor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: dispatch-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Delegate the actual parsing back to the JsonDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.vektor.dispatch_engine.*"
        spring.json.value.default.type: com.vektor.dispatch_engine.dto.deliveryevent.request.DeliveryEventUpdateRequest
        spring.json.use.type.headers: false
