package com.vektor.dispatch_engine.exception.enums;

public enum ErrorCode {
    DUPLICATE_COLUMN_NAMES,
    DRIVER_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    SETTLEMENT_ALREADY_COMPLETED,
    SETTLEMENT_ALREADY_RUNNING,
    INVALID_PAYOUT_AMOUNT,
    VALIDATION_ERROR,
    CONSTRAINT_VIOLATION,
    DUPLICATE_DELIVERY_EVENT,
    UNSUPPORTED_OPERATION,
    BANK_GATEWAY_ERROR,
    ACCESS_DENIED,
    UNAUTHORIZED,
    SYSTEM_ERROR
}
